import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './global.css';
import { Header } from '@/common/ui/header.component';
import { Footer } from '@/common/ui/footer.component';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={'dark'}>
      <body className={montserrat.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
